/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agrifarm;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.EOFException;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dilshan
 */
public class farmManagement extends javax.swing.JFrame {

    private static final String farmDB = "farmDB.ser";
    Vector<Integer> farmID = new Vector<Integer>();
    Vector farmVector = new Vector<Farm>();
    
    private Farm selectedFarm;
    private AddFieldFarm farm;
    private String assignFarmId;
    
    public farmManagement() {
        initComponents();
        showFarms();
    }

    private void showFarms() {

        try {
            Vector<Vector<String>> data = new Vector<>();
            Vector<String> header = new Vector<>();
            header.add("ID");
            header.add("Name");
            header.add("Area");
            header.add("Location");

            FileInputStream in = new FileInputStream(farmDB);
            ObjectInputStream ois;
            try {
                while (true) {
                    ois = new ObjectInputStream(in);
                    Farm newFarms = (Farm) ois.readObject();
                    Vector v = new Vector();
                    v.add(newFarms.getId());
                    v.add(newFarms.getName());
                    v.add(newFarms.getArea());

                    data.add(v);
                    
                }
            } catch (EOFException e) {

            }
            tblFarms.setModel(new DefaultTableModel(data, header));
            in.close();

        } catch (IOException e) {

      } catch (ClassNotFoundException ex) {
         
      }
         
  }

  
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<String>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnAddFarm = new javax.swing.JButton();
        btnViewField = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblFarms = new javax.swing.JTable();
        btnAddField1 = new javax.swing.JButton();

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane5.setViewportView(jTable1);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 116, 0, 215));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddFarm.setText("Add Farm");
        btnAddFarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFarmActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddFarm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnViewField.setText(" View Fields");
        btnViewField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewFieldActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, -1, -1));

        tblFarms.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Area", "Location"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblFarms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFarmsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblFarms);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 270));

        btnAddField1.setText(" Add Field");
        btnAddField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddField1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddFarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFarmActionPerformed
         addFarm obj = new addFarm();
         obj.setVisible(true);
    }//GEN-LAST:event_btnAddFarmActionPerformed

    private void btnViewFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewFieldActionPerformed
       FieldManagement obj = new FieldManagement();
       obj.setVisible(true);
    }//GEN-LAST:event_btnViewFieldActionPerformed

    private void tblFarmsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFarmsMouseClicked
         //reteive selected book index
        int row = tblFarms.getSelectedRow();
        //get bookNo from selecte row by user
        if (tblFarms.getRowSelectionAllowed()) {
            assignFarmId = tblFarms.getValueAt(row, 0).toString();
        }
    }//GEN-LAST:event_tblFarmsMouseClicked

    private void btnAddField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddField1ActionPerformed
        //selectedFarm = farm.findFarm(assignFarmId);
        System.out.println("Book selected : " + assignFarmId);
        
        AddFieldFarm obj = new AddFieldFarm();
        
        obj.str = assignFarmId;
        obj.setVisible(true); 
    }//GEN-LAST:event_btnAddField1ActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(farmManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(farmManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(farmManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(farmManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new farmManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFarm;
    private javax.swing.JButton btnAddField1;
    private javax.swing.JButton btnViewField;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblFarms;
    // End of variables declaration//GEN-END:variables
}
