/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agrifarm;

import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.UUID;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author IP
 */
public class FieldManagement extends javax.swing.JFrame {

    private static final String farmDB = "farmDB.ser";
    private static final String fieldDB = "fieldDB.ser";
    
    Vector fieldVector = new Vector<Field>();
    String farmId, farmName;
    private String assignFieldId, assignFieldName;
    /**
     * Creates new form AddField
     */
    public FieldManagement() {
        initComponents();
    }
    
    public FieldManagement(String Id, String name) {
        this.farmId = Id;
        this.farmName = name;
        initComponents();
        getFields();
        searchFields(Id);
    }
    
    public void setFieldsTable(Vector<Field> vb)
    {
        DefaultTableModel fieldTable = new DefaultTableModel();
        Vector columnName = new Vector();
        columnName.addElement("ID");
        columnName.addElement("Field Name");
        columnName.addElement("Location");
        columnName.addElement("Farm Name");
        fieldTable.setColumnIdentifiers(columnName);
        try
        {
            for(int i=0;i<vb.size();i++)
            {
                Field ff = (Field)vb.get(i);
                Vector tableData = new Vector();
                tableData.addElement(ff.getFarmId());
                tableData.addElement(ff.getName());
                tableData.addElement(ff.getLocation());
                tableData.addElement(ff.getFarmName());
                
                fieldTable.addRow(tableData);
            }
            tblFields.setModel(fieldTable);
        }
        catch(Exception e)
        {}
    }
    
    private void getFields(){
        try{

            FileInputStream in = new FileInputStream(fieldDB);
            ObjectInputStream oi;  
                try{             
                    while(true){
                        oi = new ObjectInputStream(in);
                        Field allFields = (Field) oi.readObject();
                        fieldVector.add(allFields);
                    }                
                } catch(EOFException e){

                }

            in.close();

        } catch(IOException e){} 
        catch (ClassNotFoundException ex) {}
  }
   
    
    public void searchFields(String Id){
        String searchInput = Id;
        Vector fieldSearchVector = new Vector<Field>();
        
        for(int i=0; i<fieldVector.size(); i++){
            Field fields = (Field) fieldVector.get(i);
            
            if(fields.getFarmId().equals(searchInput)){
                fieldSearchVector.add(fields);
            }
        }  
        setFieldsTable(fieldSearchVector);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFields = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Add Field");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblFields.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Location", "Farm"
            }
        ));
        tblFields.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFieldsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblFields);

        jButton2.setText("Add Plot");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("View Plots");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AddFieldFarm obj = new AddFieldFarm();
        obj.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //selectedFarm = farm.findFarm(assignFarmId);
        System.out.println("Field selected : " + assignFieldId + ", name: " + assignFieldName);
        
        AddPlot obj = new AddPlot();
        
        obj.fieldId = assignFieldId;
        obj.fieldName= assignFieldName;
        obj.setVisible(true); 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         //selectedFarm = farm.findFarm(assignFarmId);
        System.out.println("Field selected : " + assignFieldId + ", name: " + assignFieldName);
        
        PlotManagement obj = new PlotManagement(assignFieldId, assignFieldName);
        
        obj.fieldId = assignFieldId;
        obj.fieldName= assignFieldName;
        obj.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tblFieldsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFieldsMouseClicked
        int row = tblFields.getSelectedRow();
        if (tblFields.getRowSelectionAllowed()) {
            assignFieldId = tblFields.getValueAt(row, 0).toString();
            assignFieldName= tblFields.getValueAt(row, 1).toString();
        }
    }//GEN-LAST:event_tblFieldsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FieldManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FieldManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FieldManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FieldManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FieldManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFields;
    // End of variables declaration//GEN-END:variables
}
